#api网关接口代理模块配置-apisvr
Name: api
Host: 0.0.0.0
CpuThreshold: 0
Timeout: 1000000
MaxBytes: 1000000000
Port: 7777
NodeID: 1
Log:
  Encoding: plain
CacheRedis:
  - Host: 172.19.0.5:6379
    Pass:
    Type: node
Rej:
  AccessSecret: ad879037-c7a4-4063-9236-6bfc35d54b7d
  AccessExpire: 600     #过期时间单位秒
OpenAuth:
  Users:
    - UserName: nodeRed
      Password: iThings
    - UserName: root
      Password: iThings
Proxy:
  FileProxy:
    - FrontDir: ./dist
      FrontDefaultPage: front/iThingsCore/index.html
  StaticProxy:
    - Router: /api/v1/app/
      Dest: http://127.0.0.1:8000
    - Router: /api/v1/oss/
      DeletePrefix: true
      Dest: 172.19.0.10:9000
DdEnable: true
SysRpc:
  Enable: true
  Mode: direct
DmRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000
TimedJobRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000
TimedSchedulerRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000
RuleRpc:
  Enable: false
  Mode: direct
OssConf:
  OssType: minio
  PublicBucketName: ithings-public
  PrivateBucketName: ithings-private
  TemporaryBucketName: ithings-temporary
  AccessKeyID: root
  AccessKeySecret: password
  Location: 172.19.0.10:9000
  CustomHost: /api/v1/oss
  ConnectTimeout: 6000
  ReadWriteTimeout: 60000
  UseSSL: false
Event:
  Mode: natsJs
  Nats:
    Url: nats://172.19.0.2:4222